# Generated by Django 5.2.6 on 2025-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_expand_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
        migrations.RemoveField(
            model_name='server',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='server',
            name='hire_date',
        ),
    ]
